### ISSUE TITLE
Thank you, Ben

### ISSUE THREAD

**Issue by ghost** [btrask/Sequential#10]
After many years (and after trying roughly every image viewer in MacUpdate), Sequential is still my one and only image viewer for everything (images, comics, PDF docs). Even with the odd bug here and there (probably introduced with the latest OS Xs) and, quite understandable since Sequential is no longer being updated, it can't be beaten.

Just want to thank you, Ben, for developing Sequential and offering it to the Mac community.

**Comment by btrask** [comment]
You're welcome! Sorry about the bugs :)
