### ISSUE TITLE
Issue when trying to open an image file using Sequential as the default app

### ISSUE THREAD

**Issue by lardissone** [btrask/Sequential#4]
I've setup Sequential as the default .JPG file opener, and if I double click on a .JPG file, Sequential keeps loading forever.

**Comment by lardissone** [comment]
Here's the sample of the app running at 100% CPU when clicked on an image: https://gist.github.com/lardissone/d43659066f77149a5b59

**Comment by btrask** [comment]
It's busy opening the file's enclosing folder, which probably has a lot of other stuff in it.

I believe this behavior is changed ("fixed") in the latest source, but it's been a while since I've tested it.

**Comment by lardissone** [comment]
Ah yes, I've figured out. With normal folders it works amazingly!  
Based on my ignorance on how it works, I think it should ignore all files that are not images.
