### ISSUE TITLE
feature request: automatically go to next collection

### ISSUE THREAD

**Issue by riffraff** [btrask/Sequential#7]
it would be nice if at the end of a collection sequential could move to the next one, i.e. open the next cbr if the name can be detected (e.g. what mplayerx does).

Thanks for your work on sequential.

**Comment by btrask** [comment]
Open the top level directory that has all of the CBR files in it. Then Sequential will let you do full navigation between all of them.

**Comment by riffraff** [comment]
oh I never knew, thanks!
